### ISSUE TITLE
[Windows] An unsolvable puzzle!

### ISSUE THREAD

**Issue by abdullahezzat1** [SerGreen/TheWitnessPuzzles#10]
![2020-03-28 23_16_27-Window](https://user-images.githubusercontent.com/34865970/77834035-48231a00-714a-11ea-9580-2adc4e48d8a4.png)

The double triangle is impossible.

I really appreciate your work btw ❤❤

**Comment by SerGreen** [comment]
Hmm... I think it might be solvable, try this one:

![image](https://user-images.githubusercontent.com/4000373/77834299-68ec6f00-714c-11ea-89b0-01e08c9f4480.png)

Since the start piece of the line does not go all the way from top to bottom, it doesn't split the field and doesn't prevent the 2x2 square to fit, as if that line piece isn't there at all. Although i see why this is confusing. Unfortunately i didn't find a reference situation like this in The Witness to test what is the right way to handle it, so i went with what was simpler to implement. :P  
So technically not a bug.

**Comment by abdullahezzat1** [comment]
upsie 😂 sorry
