### ISSUE TITLE
Crashes on v1.0.9

### ISSUE THREAD

**Issue by sergkundel** [SerGreen/TheWitnessPuzzles#16]
Hi,
Previously I used v1.0.8 version, and it worked like charms.
Right now I installed latest (1.0.9) version.
At first it worked like expected, but after I solved 3 or 4 puzzles and skip several - I start experiencing crashes.
First crash was, when I provide correct solution and tap to confirm (finish) line.
Then I tried to enter some seed - I got crash when I click generate button.
After that I got crash when I tried to skip puzzle.

I tried to re-install apk - result was immediate crashes, when I start application.
After that I installed v1.0.8 version and it works great, without any crashes.

I don't have an idea what could go wrong.

My device: Xiaomi Mi A2 Lite (Android 10)

**Comment by SerGreen** [comment]
Thanks for letting me know.  

My best guess right now is that crashes are connected to internal storage access somehow, because it's accessed in every situation you had a crash: when you finish the line of the correct solution (current puzzle is saved to the solved panels list), when you confirm entered seed number (current puzzle is saved to the skipped panels list), when you start the application (it loads a settings file). Maybe something got corrupted when the first crash occured? Idk, i'm not convinced, because it doesn't explain why v1.0.8 works fine.  
Internal app storage is [encrypted on Android 10](https://developer.android.com/training/data-storage/app-specific) too, so you can't just open it and see if everything is ok.  

But still, since v1.0.9 worked fine for you at first, it's likely that bad user data is the cause after all. I'd suggest trying to clear application data and see if it helps. Note that it will reset settings and erase all saved puzzles if you have any, so if you want to keep them, open them in v1.0.8 and write down their seed numbers at the top of the screen, so that you can regenerate them later in v1.0.9.  

**Here are the steps for what i suggest:**  
1. [Optional] Open v1.0.8 and write down seeds of your saved puzzles.
2. Install v1.0.9. Don't open it yet.
3. Find TWP in application manager in settings (or long press on TWP in app drawer and select "App info").
4. At the bottom of the info screen select `Clear data` (see screenshot below).
5. Try launching v1.0.9 now.

<img src="https://user-images.githubusercontent.com/4000373/125529030-407f695b-ad85-40ae-b692-df21c87fbaae.jpg" width=480 />

**Comment by sergkundel** [comment]
I did as you suggested: installed 1.0.9 (without run), clean data, start application.
Once again solved 2 puzzles, skip several, tried to generate seed - crash.
Cleaned data again.
This time I was just generating some seeds. And on 4th attempt I got crash.

Looked more deeply:
First I thought that specific puzzle element is crashing, when try to save it, but it seems like no.
Cleaned data 10-15 times again - constantly got crash when I tried to skip (no other actions are performed) 3rd or 4th puzzle.
Examples:
triangles + squares
symmetry + star + triangles + eraser
symmetry + star + squares + dots
symmetry + star + triangles + squares (crash)

symmetry + star + triangles + tetris
symmetry + star + triangles + tetris
star + triangles + squares + tetris + dots (crash)

symmetry + star + triangles + squares
star + triangles + tetris
triangles + squares + dots
symmetry + triangles + star + dots (crash)

**Comment by SerGreen** [comment]
So weird. For you these crashes seem to be consistent(-ish), but i can't get it to crash on my Xiaomi (Poco) M3 with Android 10.  
___  
Huh. It turns out that you can't debug on a Xiaomi phone without logging in to Mi account. What a ridiculous restriction. I think i won't buy another Xiaomi now.  
___  
So i tried to change a way data is saved: replaced isolated encrypted storage with a folder in external memory. And i tried to add a message popup in case of a crash, so we could get at least some information about the error your phone encounters. BUT! Now it crashes on start on my phone and i can't debug it because of Mi account. So i fetched an old Samsung to debug it there, but it works just fine on Samsung. I don't even...  

So i gotta figure out what's up with this experimental build first before we can get closer to the source of crashes on your phone.

**Comment by SerGreen** [comment]
@sergkundel  
Okay, here we go. Not sure what it was, but after building in Release configuration and signing the apk it works on my Poco M3. Let's hope it does on your Mi A2 Lite as well.  

So here's an experimental build `v1.0.9f` to help us trace your bug: https://github.com/SerGreen/TheWitnessPuzzles/releases/tag/v1.0.9f  
When it crashes it _should_ display a message like on the screenshot below. Make a screenshot of it once it crashes on your phone and post it here. Also i hardwired the Volume Down button to force crash it in order to test that it works.  

<img src="https://user-images.githubusercontent.com/4000373/126017856-d1739884-5165-40b2-9674-a2aeecc41f43.jpg" width=480 />  

Additionally, the game now saves puzzles and settings in `/Android/data/com.sergreen.thewitnesspuzzles/files/`, so you can check it and see if anything is wrong when it starts crashing.  
___
Try the following to help us narrow down what causes the crash: 
1. Back up the `settings.cfg` from the saves folder before it starts to crash
2. When it starts to crash, open folder with saves and restore `settings.cfg` from the backup. See if it still crashes on startup.
3. If yes, then try to delete everything from saves folder and restore only the `settings.cfg` from the backup. See if it still crashes.
4. If yes, then try to delete everything in saves folder, including settings. See if it still crashes.
5. If it still crashes even after clearing saves folder, then i dunno, let's hope that error message will offer some helpful insights.

___  

EDIT: It should install normally on top of v1.0.9, but if it fails to install, then delete v1.0.9 first and then install v1.0.9f.

**Comment by sergkundel** [comment]
Ok, I did some investigation. in general it's file not found error.

Here I'll provide details for discarded puzzles (the same issue is for solved puzzles).
Steps:
1. Install 1.0.9f, run application (to generate folder structure), exit.
2. In file explorer `lastDiscarded` folder is empty.
3. Run app, click Start, click Skip puzzle, exit.
4. In `lastDiscarded` folder I have: `discarder000_402961986.panel`
5. Run app, click Start, click Skip puzzle, exit.
6. In `lastDiscarded` folder I have: `discarder001_402961986.panel`, `discarder000_843494858.panel`
7. Run app, click Start, click Skip puzzle, got crash: file not found `discarder001_843494858.panel`
8. In `lastDiscarded` folder I have: `discarder001_402961986.panel`, `discarder000_843494858.panel`
Actually on Sunday I constantly get crash on 4th puzzle (not 3rd one as here), but it's the same issue.

![Screenshot_20210719-120938](https://user-images.githubusercontent.com/87384986/126134991-e29e19db-0d34-484b-aff4-36d953830d2f.png)

I don't know why you using Linux like "log rotation" logic here, with renaming files, to have latest one with 000 (maybe there is some hidden reason). As for me, you can rewrite this logic with simple sorting files by Created attribute (preferably) or by name (in this case additional logic will be required to sort files after 999 puzzle index) and, when you have more that 10, remove last created one. In any case don't forget to add some IF for 999 index of puzzle, to start again with 000 after 999.

So, take a look into `AddPanelToLastNList` function in `TWP Shared\Support Classes\FileStorageManager.cs`.

**Comment by SerGreen** [comment]
Thank you, finally it's obvious what's up!  

Now that you say it, i also don't know why i chose to embed puzzle number into the file name, using 'Last Modified' attribute seems like an obvious choice. I guess it was the first thing that came to my mind at that time and it just worked right away, so it stayed.  

The issue here is that my code retrieves list of files with `storage.GetFileNames()` and later assumes that `fileName[5]` has the name `discarded005...`, which was the case for my devices so far, but not for yours. It's surprising that it took so long for this bug to pop up, you can't just assume that list of files will be sorted by default.  

Anyways, i'll fix this soon and publish it as v1.0.10. I think i'll leave the saves in external memory and message on crash, it should help for any future bugs.

**Comment by sergkundel** [comment]
Ok, don't forget to remove crash event from Volume Down button :)

**Comment by SerGreen** [comment]
Done!  
New version is available here: https://github.com/SerGreen/TheWitnessPuzzles/releases/tag/v1.0.10.
