### ISSUE TITLE
[Maybe?]Potential unresolvable puzzles

### ISSUE THREAD

**Issue by dovisutu** [SerGreen/TheWitnessPuzzles#22]
Version: 1.0.11

Seed: 000000033 (Yeah, sequential mode)

I'm not sure if it's really unsoluable or if I just dumbed over it, but this symmetry puzzle doesn't appear to be valid. I don't see there's any way to put any shape into the same sector as the left elimination is in.

![Screenshot_20221220-094530.jpg](https://user-images.githubusercontent.com/40313014/208564511-9bf2425f-23e6-447c-9579-9d7e0cd434b9.jpg)

I suspect it might have something to do with #5 which reports a similar issue, though I would assume it should've been resolved; I actually did manage to find a potential _solution_ that matches the condition for #5 to happen:

![Screenshot_20221220-100734.jpg](https://user-images.githubusercontent.com/40313014/208564546-7b5738fe-1c54-4532-bf87-9ccf2a7eabe0.jpg)

Not sure if this is really the line used to generate the puzzle though.

**Comment by SerGreen** [comment]
You god damn right, this is a bug in the generator! It is indeed connected to the issue #5, turns out that the pull request #7 fixed only one part of the issue and i didn't realise that there's more to it.  

Anyways, i followed the generation process step by step in a debugger and can confirm that the solution you suggested here is indeed the one that should be correct. When generating Eliminator rules it picks a Sector that consists of Block 10. This Sector has only one Block and no free corner Nodes or free Edges (the only edge is already a Broken Edge).  

**The generator decides to generate a fake Hexagon rule for the Eliminator rule to eliminate, but it fails to find an empty spot for it, so it creates an Eliminator that has nothing to eliminate.**  

![image](https://user-images.githubusercontent.com/4000373/208670597-2a943874-e653-4914-8546-763408714b40.png)

**Comment by SerGreen** [comment]
It should be fixed with [v1.0.12 release](https://github.com/SerGreen/TheWitnessPuzzles/releases/tag/v1.0.12). Also i added a check at the end of the generation process that should prevent generation of impossible puzzles in the future. Hopefully there will be no more impossible puzzles in the future, though.  

The new version of Seed 000000033 looks like this now:  
![image](https://user-images.githubusercontent.com/4000373/209451364-b21b27c3-ac9c-4415-91f9-596acb381a2d.png)
